spring.application.name=evt-open-service
server.port=8081

event.core.grpc.host=${EVENT_CORE_GRPC_HOST:localhost}
event.core.grpc.port=${EVENT_CORE_GRPC_PORT:9090}
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}