spring.application.name=evt-notification-service

server.port=8083

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/evently}